FROM debian:latest
RUN apt update && apt upgrade -y
RUN apt install wget -y
RUN wget https://sourceforge.net/projects/subread/files/subread-2.0.6/subread-2.0.6-Linux-x86_64.tar.gz
RUN tar -xf /subread-2.0.6-Linux-x86_64.tar.gz